/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import javax.swing.DefaultListModel;
import java.util.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import persistencia.ControladorPersistencia;
import logica.*;

/**
 *
 * @author Chama
 */
public class AltaCurso extends javax.swing.JInternalFrame {

    private ControladorPersistencia cp;
    private DefaultListModel<String> modeloDisponibles;
    private DefaultListModel<String> modeloPrevias;
    /**
     * Creates new form AltaCurso
     */
    public AltaCurso(ControladorPersistencia cp) {
        initComponents();
        
        this.cp = cp;
        
        modeloDisponibles = new DefaultListModel<>();
        modeloPrevias = new DefaultListModel<>();
        
        
        ArrayList<Curso> cursos = cp.listarCursos();
        
        for(int i = 0; i < cursos.size(); i++)
        {
            Curso curso = cursos.get(i);
            modeloDisponibles.addElement(curso.getNombre());
        }
        ListaCursosDisponibles.setModel(modeloDisponibles);
        ListaPreviasSeleccionadas.setModel(modeloPrevias);
        
        ComboInstitutoCurso.removeAllItems();
        ArrayList<Instituto> institutos = cp.listarInstitutos();
        
        for(int i= 0; i < institutos.size(); i++)
        {
            ComboInstitutoCurso.addItem(institutos.get(i).getNombre());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    private ArrayList<Curso> cursos = new ArrayList<>();
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ComboInstitutoCurso = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCurso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionCurso = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtDuracionCurso = new javax.swing.JTextField();
        txtCantidadHorasCurso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCreditosCurso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtURLCurso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaCursosDisponibles = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaPreviasSeleccionadas = new javax.swing.JList<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALTA DE CURSO");

        jLabel2.setText("Instituto: ");

        ComboInstitutoCurso.addActionListener(this::ComboInstitutoCursoActionPerformed);

        jLabel3.setText("Nombre:");

        jLabel4.setText("Descripción:");

        txtDescripcionCurso.setColumns(20);
        txtDescripcionCurso.setRows(5);
        jScrollPane1.setViewportView(txtDescripcionCurso);

        jLabel6.setText("Duración:");

        txtCantidadHorasCurso.addActionListener(this::txtCantidadHorasCursoActionPerformed);

        jLabel7.setText("Cantidad de horas:");

        jLabel8.setText("Créditos:");

        jLabel5.setText("URL:");

        jLabel9.setText("Cursos disponibles");

        ListaCursosDisponibles.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListaCursosDisponibles);

        jLabel10.setText("Previas seleccionadas");

        ListaPreviasSeleccionadas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(ListaPreviasSeleccionadas);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(this::btnQuitarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(51, 51, 51))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(69, 69, 69)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComboInstitutoCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreCurso)
                    .addComponent(jScrollPane1)
                    .addComponent(txtCreditosCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addComponent(txtCantidadHorasCurso)
                    .addComponent(txtDuracionCurso)
                    .addComponent(txtURLCurso)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btnAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar))
                        .addGap(17, 17, 17)))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuitar)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboInstitutoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDuracionCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadHorasCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCreditosCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtURLCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptar)
                            .addComponent(btnCancelar))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQuitar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboInstitutoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboInstitutoCursoActionPerformed
        // TODO add your handling code here:
        
        String nombreInstituto = (String) ComboInstitutoCurso.getSelectedItem();
        
        modeloDisponibles.clear();
        modeloPrevias.clear();
        
        ArrayList<Curso> cursosDelInstituto = cp.listarCursosPorInstituto(nombreInstituto);
        
        for(int i = 0; i < cursosDelInstituto.size(); i++)
        {
            Curso curso = cursosDelInstituto.get(i);
            
            modeloDisponibles.addElement(curso.getNombre());
        }
        
    }//GEN-LAST:event_ComboInstitutoCursoActionPerformed

    private void txtCantidadHorasCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadHorasCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadHorasCursoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
try {
    String nombreInstituto = (String) ComboInstitutoCurso.getSelectedItem();
    if (nombreInstituto == null) throw new IllegalArgumentException("Seleccione un instituto.");
    Instituto instituto = cp.buscarInstituto(nombreInstituto);
    if (instituto == null) throw new IllegalArgumentException("El instituto ya no existe.");
    String nombre = txtNombreCurso.getText().trim();
    String descripcion = txtDescripcionCurso.getText().trim();
    String duracion = txtDuracionCurso.getText().trim();
    String url = txtURLCurso.getText().trim();
    if (nombre.isEmpty() || descripcion.isEmpty() || duracion.isEmpty() || url.isEmpty()) {
        throw new IllegalArgumentException("Complete nombre, descripción, duración y URL.");
    }
    int horas = Integer.parseInt(txtCantidadHorasCurso.getText().trim());
    int creditos = Integer.parseInt(txtCreditosCurso.getText().trim());
    if (cp.existeCurso(nombre)) throw new IllegalArgumentException("Ya existe ese nombre de curso en la plataforma.");
    Set<Curso> previas = new HashSet<>();
    for (int i = 0; i < modeloPrevias.size(); i++) {
        Curso previa = cp.buscarCurso(modeloPrevias.getElementAt(i));
        if (previa == null) throw new IllegalArgumentException("Una previa seleccionada ya no existe.");
        previas.add(previa);
    }
    Curso curso = new Curso(nombre, duracion, horas, creditos,
            LocalDate.now(), descripcion, url);
    curso.setInstituto(instituto);
    curso.setPrevias(previas);
    cp.altaCurso(curso);
    JOptionPane.showMessageDialog(this, "Curso creado correctamente.");
    dispose();
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Horas y créditos deben ser números enteros.");
} catch (RuntimeException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, e.getMessage(), "No se creó el curso", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
String seleccionado = ListaCursosDisponibles.getSelectedValue();
if (seleccionado == null) return;
if (!modeloPrevias.contains(seleccionado)) modeloPrevias.addElement(seleccionado);
modeloDisponibles.removeElement(seleccionado);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
String seleccionado = ListaPreviasSeleccionadas.getSelectedValue();
if (seleccionado == null) return;
if (!modeloDisponibles.contains(seleccionado)) modeloDisponibles.addElement(seleccionado);
modeloPrevias.removeElement(seleccionado);
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboInstitutoCurso;
    private javax.swing.JList<String> ListaCursosDisponibles;
    private javax.swing.JList<String> ListaPreviasSeleccionadas;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtCantidadHorasCurso;
    private javax.swing.JTextField txtCreditosCurso;
    private javax.swing.JTextArea txtDescripcionCurso;
    private javax.swing.JTextField txtDuracionCurso;
    private javax.swing.JTextField txtNombreCurso;
    private javax.swing.JTextField txtURLCurso;
    // End of variables declaration//GEN-END:variables
}
