/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Set;
import persistencia.ControladorPersistencia;
import logica.*;
/**
 *
 * @author Chama
 */
public class ConsultaCurso extends javax.swing.JInternalFrame {
    
    
private ControladorPersistencia cp;

public void seleccionarCurso(String nombre) {
    Curso curso = cp.buscarCurso(nombre);
    if (curso == null || curso.getInstituto() == null) {
        throw new IllegalArgumentException("El curso ya no está disponible.");
    }
    ComboInstitutoConsulta.setSelectedItem(curso.getInstituto().getNombre());
    ComboCursoConsulta.setSelectedItem(nombre);
}

private void limpiarDetalleCurso() {
    txtNombreInstituto.setText("");
    txtDescripcionCurso.setText("");
    txtDuracionCurso.setText("");
    txtHorasCurso.setText("");
    txtCreditosCurso.setText("");
    txtFechaCurso.setText("");
    txturlCurso.setText("");
    ListaPreviasCurso.setModel(new DefaultListModel<>());
    ListaEdiciones.setModel(new DefaultListModel<>());
}
    /**
     * Creates new form ConsultaCurso
     */
    public ConsultaCurso(ControladorPersistencia cp) {
        
        this.cp = cp;
        initComponents();
        
        ComboInstitutoConsulta.removeAllItems();
        ComboCursoConsulta.removeAllItems();
        
        ArrayList<Instituto> institutos = cp.listarInstitutos();
        
        for(int i = 0; i < institutos.size(); i++)
        {
            ComboInstitutoConsulta.addItem(institutos.get(i).getNombre());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreInstituto = new javax.swing.JTextField();
        txtDescripcionCurso = new javax.swing.JTextField();
        txtDuracionCurso = new javax.swing.JTextField();
        txtHorasCurso = new javax.swing.JTextField();
        txtCreditosCurso = new javax.swing.JTextField();
        txtFechaCurso = new javax.swing.JTextField();
        txturlCurso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPreviasCurso = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        ComboInstitutoConsulta = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        ComboCursoConsulta = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaEdiciones = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta Curso");

        jLabel2.setText("Nombre de curso:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Instituto:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Descripción:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Duración:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Horas:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Créditos:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Fecha:");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("URL:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Previas:");

        txtNombreInstituto.setEditable(false);

        txtDescripcionCurso.setEditable(false);

        txtDuracionCurso.setEditable(false);

        txtHorasCurso.setEditable(false);

        txtCreditosCurso.setEditable(false);

        txtFechaCurso.setEditable(false);

        txturlCurso.setEditable(false);

        jScrollPane1.setViewportView(ListaPreviasCurso);

        jLabel12.setText("Instituto:");

        ComboInstitutoConsulta.addActionListener(this::ComboInstitutoConsultaActionPerformed);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        ComboCursoConsulta.addActionListener(this::ComboCursoConsultaActionPerformed);

        jScrollPane2.setViewportView(ListaEdiciones);

        jLabel13.setText("Ediciones:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel13))
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ComboInstitutoConsulta, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE)
                            .addComponent(ComboCursoConsulta, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcionCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDuracionCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHorasCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCreditosCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txturlCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ComboInstitutoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboCursoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDescripcionCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDuracionCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHorasCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCreditosCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFechaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txturlCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void ComboCursoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCursoConsultaActionPerformed
limpiarDetalleCurso();
String nombreInstituto = (String) ComboInstitutoConsulta.getSelectedItem();
String nombreCurso = (String) ComboCursoConsulta.getSelectedItem();
if (nombreInstituto == null || nombreCurso == null) return;
try {
    Instituto instituto = cp.buscarInstituto(nombreInstituto);
    if (instituto == null) throw new IllegalArgumentException("El instituto ya no existe.");
    Curso curso = cp.buscarCursoInstituto(nombreCurso, instituto);
    if (curso == null) throw new IllegalArgumentException("El curso ya no existe.");
    DefaultListModel<String> previas = new DefaultListModel<>();
    for (Curso previa : curso.getPrevias()) previas.addElement(previa.getNombre());
    DefaultListModel<String> ediciones = new DefaultListModel<>();
    for (EdicionCurso edicion : cp.listarEdicionesCurso(curso)) ediciones.addElement(edicion.getNombre());
    txtNombreInstituto.setText(instituto.getNombre());
    txtDescripcionCurso.setText(curso.getDescripcion());
    txtDuracionCurso.setText(curso.getDuracion());
    txtHorasCurso.setText(String.valueOf(curso.getCantidadHoras()));
    txtCreditosCurso.setText(String.valueOf(curso.getCreditos()));
    txtFechaCurso.setText(curso.getFechaRegistro() == null ? "" : curso.getFechaRegistro().toString());
    txturlCurso.setText(curso.getUrl());
    ListaPreviasCurso.setModel(previas);
    ListaEdiciones.setModel(ediciones);
} catch (RuntimeException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "No se pudo consultar el curso: " + e.getMessage());
}
    }//GEN-LAST:event_ComboCursoConsultaActionPerformed

    private void ComboInstitutoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboInstitutoConsultaActionPerformed
        // TODO add your handling code here:
        
        String nombreInstituto = (String) ComboInstitutoConsulta.getSelectedItem();
        
        if(nombreInstituto == null)
        {
            return;
        }
        
        ComboCursoConsulta.removeAllItems();
        
        ArrayList<Curso> cursos = cp.listarCursosPorInstituto(nombreInstituto);
        
        for(int i = 0; i < cursos.size(); i++)
        {
            ComboCursoConsulta.addItem(cursos.get(i).getNombre());
        }
    }//GEN-LAST:event_ComboInstitutoConsultaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCursoConsulta;
    private javax.swing.JComboBox<String> ComboInstitutoConsulta;
    private javax.swing.JList<String> ListaEdiciones;
    private javax.swing.JList<String> ListaPreviasCurso;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCreditosCurso;
    private javax.swing.JTextField txtDescripcionCurso;
    private javax.swing.JTextField txtDuracionCurso;
    private javax.swing.JTextField txtFechaCurso;
    private javax.swing.JTextField txtHorasCurso;
    private javax.swing.JTextField txtNombreInstituto;
    private javax.swing.JTextField txturlCurso;
    // End of variables declaration//GEN-END:variables
}
