/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;
import java.util.List;
import persistencia.ControladorPersistencia;
import logica.Instituto;
import logica.Curso;
import logica.EdicionCurso;
import logica.Estudiante;
import javax.swing.*;

/**
 *
 * @author Nicolás
 */
public class InscripcionAEdicionDeCursoInternalFrame extends javax.swing.JInternalFrame {

    
    private ControladorPersistencia cp;
    
    private Estudiante estudianteSeleccionado;
    private EdicionCurso edicionSeleccionada;
    
    public InscripcionAEdicionDeCursoInternalFrame(ControladorPersistencia cp) {
        initComponents();
        FechasFormulario.configurar(dcInscripcion);
        FechasFormulario.mostrar(dcInscripcion, java.time.LocalDate.now());
        estudianteSeleccionadoTXT.setVisible(false);
        jButton2.setEnabled(false);
        this.cp = cp;
        
        setSize(750, 500);
        cargarInstitutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        EdicionVigenteTXT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        estudianteSeleccionadoTXT = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        dcInscripcion = new com.toedter.calendar.JDateChooser();

        jLabel3.setText("jLabel3");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Inscripción a Edicion de Curso");

        jLabel1.setText("Instituto:");

        jComboBox1.addActionListener(this::jComboBox1SeleccionoInstituto);

        jLabel2.setText("Curso: ");

        jComboBox2.addActionListener(this::jComboBox2SeleccionoCursoDeInstituto);

        jLabel4.setText("Edición:");

        EdicionVigenteTXT.setEditable(false);
        EdicionVigenteTXT.addActionListener(this::EdicionVigenteTXTActionPerformed);

        jButton1.setText("Seleccionar Estudiante");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel6.setText("Estudiante: ");

        estudianteSeleccionadoTXT.setText("Estudiante seleccionado");

        jButton2.setText("Aceptar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Cancelar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel7.setText("Fecha Inscripción:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(dcInscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EdicionVigenteTXT))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estudianteSeleccionadoTXT)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(EdicionVigenteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(dcInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(estudianteSeleccionadoTXT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(33, 33, 33))
        );

        estudianteSeleccionadoTXT.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
private void actualizarBotonInscripcion() {
    jButton2.setEnabled(estudianteSeleccionado != null
            && jComboBox2.getSelectedItem() != null && edicionSeleccionada != null);
}

private void cargarInstitutos() {
        jComboBox1.removeAllItems();

        List<Instituto> institutos = cp.obtenerInstitutos();

        for (Instituto instituto : institutos) {
        jComboBox1.addItem(instituto);
        }
    }
    
    private void jComboBox1SeleccionoInstituto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1SeleccionoInstituto
edicionSeleccionada = null;
EdicionVigenteTXT.setText("No hay edición vigente");
jComboBox2.removeAllItems();
actualizarBotonInscripcion();
Instituto instituto = (Instituto) jComboBox1.getSelectedItem();
if (instituto == null) return;
try {
    for (Curso curso : cp.obtenerCursosDeInstituto(instituto.getId())) {
        jComboBox2.addItem(curso);
    }
} catch (RuntimeException e) {
    JOptionPane.showMessageDialog(this, "No se pudieron cargar los cursos.");
    e.printStackTrace();
}
    }//GEN-LAST:event_jComboBox1SeleccionoInstituto

    private void jComboBox2SeleccionoCursoDeInstituto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2SeleccionoCursoDeInstituto
edicionSeleccionada = null;
EdicionVigenteTXT.setText("No hay edición vigente");
actualizarBotonInscripcion();
Curso curso = (Curso) jComboBox2.getSelectedItem();
if (curso == null) return;
try {
    java.util.List<EdicionCurso> vigentes = new java.util.ArrayList<>();
    for (EdicionCurso edicion : cp.listarEdicionesCurso(curso)) {
        if (edicion.esVigente()) vigentes.add(edicion);
    }
    if (vigentes.size() == 1) {
        edicionSeleccionada = vigentes.get(0);
        EdicionVigenteTXT.setText(edicionSeleccionada.getNombre());
    } else if (vigentes.size() > 1) {
        EdicionVigenteTXT.setText("Hay varias ediciones vigentes; revise sus fechas");
    }
} catch (RuntimeException e) {
    JOptionPane.showMessageDialog(this, "No se pudieron cargar las ediciones.");
    e.printStackTrace();
}
actualizarBotonInscripcion();
    }//GEN-LAST:event_jComboBox2SeleccionoCursoDeInstituto

    private void EdicionVigenteTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdicionVigenteTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdicionVigenteTXTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        List<Estudiante> estudiantes = cp.obtenerEstudiantes();

        if (estudiantes.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "No hay estudiantes registrados."
            );
            return;
        }

        Estudiante seleccionado = (Estudiante) JOptionPane.showInputDialog(
            this,
            "Seleccione un estudiante:",
            "Estudiantes",
            JOptionPane.PLAIN_MESSAGE,
            null,
            estudiantes.toArray(),
            estudiantes.get(0)
        );
    
        if (seleccionado != null) {
            estudianteSeleccionado = seleccionado;
            estudianteSeleccionadoTXT.setText(seleccionado.getNombre());
estudianteSeleccionadoTXT.setVisible(true);
actualizarBotonInscripcion();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Estudiante estudiante = estudianteSeleccionado;
Curso curso = (Curso) jComboBox2.getSelectedItem();
EdicionCurso edicion = edicionSeleccionada;
if (estudiante == null || curso == null || edicion == null) {
    JOptionPane.showMessageDialog(this, "Seleccione estudiante y un curso con edición vigente.");
    return;
}
java.time.format.DateTimeFormatter formato = java.time.format.DateTimeFormatter
        .ofPattern("dd/MM/uuuu").withResolverStyle(java.time.format.ResolverStyle.STRICT);
try {
    java.time.LocalDate fecha = FechasFormulario.leer(
        dcInscripcion, "la fecha de inscripción"
    );
    String mensaje = "Inscribir a " + estudiante.getNick() + " en " + edicion.getNombre()
            + " del curso " + curso.getNombre() + ", con fecha " + fecha.format(formato) + ".";
    if (JOptionPane.showConfirmDialog(this, mensaje, "Confirmar inscripción",
            JOptionPane.OK_CANCEL_OPTION) != JOptionPane.OK_OPTION) return;
    cp.inscriboAEdicionCurso(estudiante, edicion, fecha);
    JOptionPane.showMessageDialog(this, "Inscripción realizada correctamente.");
    estudianteSeleccionado = null;
    estudianteSeleccionadoTXT.setText("");
    estudianteSeleccionadoTXT.setVisible(false);
    actualizarBotonInscripcion();
} catch (RuntimeException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, e.getMessage(), "No se realizó la inscripción", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EdicionVigenteTXT;
    private com.toedter.calendar.JDateChooser dcInscripcion;
    private javax.swing.JLabel estudianteSeleccionadoTXT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<Instituto> jComboBox1;
    private javax.swing.JComboBox<Curso> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
