/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;


import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.ArrayList;
import logica.ControladorUsuario;

/**
 *
 * @author adrie
 */
public class InternalConsultaUsuario extends javax.swing.JInternalFrame {

    private ControladorUsuario control;
    
    public InternalConsultaUsuario(ControladorUsuario control) {
        initComponents();
        this.control = control;
        
        jScrollPane1.setPreferredSize(new java.awt.Dimension(280, 160));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(280, 160));

        cargarUsuariosEnCombo();

        setTitle("Consulta de usuario");
        setSize(700, 500);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(true);
    }

    
    
    
    private void cargarUsuariosEnCombo() {
    cmbUsuarios.removeAllItems();
    List<String> nickname = control.listarNicknamesUsuarios();
    
    for (String nick : nickname) {
        cmbUsuarios.addItem(nick);
    }
    
    // Dejamos la selección vacía al principio para que no cargue datos por accidente
    cmbUsuarios.setSelectedIndex(-1); 
}
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbUsuarios = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtFechaNac = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCursosEdiciones = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProgramas = new javax.swing.JList<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Seleccionar Usuario");

        cmbUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUsuarios.addActionListener(this::cmbUsuariosActionPerformed);

        txtNombre.setEditable(false);

        txtApellido.setEditable(false);

        txtMail.setEditable(false);

        txtFechaNac.setEditable(false);

        lstCursosEdiciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCursosEdiciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCursosEdicionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstCursosEdiciones);

        lstProgramas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstProgramas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProgramasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstProgramas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombre)
                                .addComponent(txtApellido)
                                .addComponent(txtMail)
                                .addComponent(txtFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuariosActionPerformed
txtNombre.setText("");
txtApellido.setText("");
txtMail.setText("");
txtFechaNac.setText("");
javax.swing.DefaultListModel<String> academico = new javax.swing.DefaultListModel<>();
javax.swing.DefaultListModel<String> programas = new javax.swing.DefaultListModel<>();
lstCursosEdiciones.setModel(academico);
lstProgramas.setModel(programas);
if (cmbUsuarios.getSelectedItem() == null) return;
try {
    String nick = cmbUsuarios.getSelectedItem().toString();
    logica.Usuario usuario = control.obtenerUsuarioPorNickname(nick);
    if (usuario == null) throw new IllegalArgumentException("El usuario ya no existe.");
    txtNombre.setText(usuario.getNombre());
    txtApellido.setText(usuario.getApellido());
    txtMail.setText(usuario.getMail());
    txtFechaNac.setText(usuario.getFechaNacimiento() == null ? "No registrada"
            : usuario.getFechaNacimiento().format(DateTimeFormatter.ofPattern("dd/MM/uuuu")));
    boolean docente = usuario instanceof logica.Docente;
    lstCursosEdiciones.setBorder(javax.swing.BorderFactory.createTitledBorder(
            docente ? "Cursos del docente" : "Ediciones inscriptas"));
    lstProgramas.setBorder(javax.swing.BorderFactory.createTitledBorder(
            docente ? "Programas relacionados con sus cursos" : "Programas inscriptos"));
    for (String nombre : control.listarCursosOEdicionesUsuario(nick)) academico.addElement(nombre);
    for (String nombre : control.listarProgramasUsuario(nick)) programas.addElement(nombre);
} catch (RuntimeException e) {
    e.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "No se pudo completar la consulta: "
            + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_cmbUsuariosActionPerformed

    private void lstCursosEdicionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCursosEdicionesMouseClicked
if (evt.getClickCount() != 2 || lstCursosEdiciones.getSelectedValue() == null
        || cmbUsuarios.getSelectedItem() == null || getDesktopPane() == null) return;
try {
    String nombre = lstCursosEdiciones.getSelectedValue();
    logica.Usuario usuario = control.obtenerUsuarioPorNickname(cmbUsuarios.getSelectedItem().toString());
    if (usuario == null) throw new IllegalArgumentException("El usuario ya no existe.");
    persistencia.ControladorPersistencia cp = new persistencia.ControladorPersistencia();
    javax.swing.JInternalFrame ventana;
    if (usuario instanceof logica.Docente) {
        ConsultaCurso consulta = new ConsultaCurso(cp);
        consulta.seleccionarCurso(nombre);
        ventana = consulta;
    } else {
        ConsultaEdicionDeCursoInternalFrame consulta = new ConsultaEdicionDeCursoInternalFrame(cp);
        consulta.seleccionarEdicion(nombre);
        ventana = consulta;
    }
    getDesktopPane().add(ventana);
    ventana.setVisible(true);
    ventana.toFront();
} catch (RuntimeException e) {
    e.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "No se pudo abrir la consulta: " + e.getMessage());
}
    }//GEN-LAST:event_lstCursosEdicionesMouseClicked

    private void lstProgramasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProgramasMouseClicked
if (evt.getClickCount() != 2 || lstProgramas.getSelectedValue() == null || getDesktopPane() == null) return;
try {
    persistencia.ControladorPersistencia cp = new persistencia.ControladorPersistencia();
    ConsultaProgramaFormacionInternalFrame ventana = new ConsultaProgramaFormacionInternalFrame(cp);
    ventana.seleccionarPrograma(lstProgramas.getSelectedValue());
    getDesktopPane().add(ventana);
    ventana.setVisible(true);
    ventana.toFront();
} catch (RuntimeException e) {
    e.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "No se pudo abrir el programa: " + e.getMessage());
}
    }//GEN-LAST:event_lstProgramasMouseClicked


    
    
    
    
    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstCursosEdiciones;
    private javax.swing.JList<String> lstProgramas;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
