/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import logica.IServidorCentral;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;


/**
 *
 * @author adrie
 */
public class InternalModificarUsuario extends javax.swing.JInternalFrame {

    private IServidorCentral servidorCentral;
    
    public InternalModificarUsuario(IServidorCentral servidorCentral) {
        initComponents();
        FechasFormulario.configurar(dcNacimiento);
        this.servidorCentral = servidorCentral;
        
        cargarUsuariosEnCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbUsuarios = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();
        dcNacimiento = new com.toedter.calendar.JDateChooser();

        lblContrasena = new javax.swing.JLabel();
        lblConfirmacion = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        txtConfirmacion = new javax.swing.JPasswordField();
        lblContrasena.setText("Nueva contraseña:");
        lblConfirmacion.setText("Confirmar contraseña:");
        txtContrasena.setToolTipText("Deje ambos campos vacíos para conservar la contraseña actual.");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modificar Usuario");

        jLabel1.setText("Usuario a modificar");

        cmbUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUsuarios.addActionListener(this::cmbUsuariosActionPerformed);

        txtNombre.setText("Nombre");

        txtApellido.setText("Aapellido");

        btnGuardar.setText("Guardar Cambios");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        txtCorreo.setEditable(false);
        txtCorreo.setText("Correo");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Correo Electronico:");

        jLabel5.setText("Fecha Nacimiento:");

        jLabel6.setText("Nickname:");

        txtNickname.setEditable(false);
        txtNickname.setText("Nickname");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(lblContrasena)
                        .addComponent(lblConfirmacion)
                        .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(txtNickname, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(txtConfirmacion, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(dcNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                    .addContainerGap())
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnGuardar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasena)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmacion)
                    .addComponent(txtConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dcNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar))
                .addContainerGap()
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void cargarUsuariosEnCombo() {
        cmbUsuarios.removeAllItems();
        
        java.util.List<String> nicknames = servidorCentral.listarNicknamesUsuarios();
        for (String nick : nicknames) {
            cmbUsuarios.addItem(nick);
        }
        cmbUsuarios.setSelectedIndex(-1);
    }
    
    
    
    
    private void cmbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuariosActionPerformed
       if (servidorCentral == null) return;
       txtContrasena.setText("");
       txtConfirmacion.setText("");
       if (cmbUsuarios.getSelectedItem() == null) {
            return;
        }

        String nickSeleccionado = cmbUsuarios.getSelectedItem().toString();
        logica.Usuario u = servidorCentral.obtenerUsuario(nickSeleccionado);

        if (u != null) {
            txtNickname.setText(u.getNick()); 
            txtCorreo.setText(u.getMail());
            txtNombre.setText(u.getNombre());
            txtApellido.setText(u.getApellido());
            if (u.getFechaNacimiento() != null) {
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            FechasFormulario.mostrar(
            dcNacimiento, u.getFechaNacimiento()
            );
        } else {
            dcNacimiento.setDate(null);
        }       
                }
    }//GEN-LAST:event_cmbUsuariosActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
if (cmbUsuarios.getSelectedItem() == null) {
    javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un usuario primero.");
    return;
}
String clave = new String(txtContrasena.getPassword());
String confirmacion = new String(txtConfirmacion.getPassword());
try {
    String nick = cmbUsuarios.getSelectedItem().toString();
    String nombre = txtNombre.getText().trim();
    String apellido = txtApellido.getText().trim();
    LocalDate fecha = FechasFormulario.leer(
        dcNacimiento, "la fecha de nacimiento"
    );
    servidorCentral.modificarUsuario(nick, nombre, apellido, fecha, clave, confirmacion);
    javax.swing.JOptionPane.showMessageDialog(this, "Usuario modificado con éxito.");
    dispose();
} catch (RuntimeException e) {
    e.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
            "No se guardaron los cambios", javax.swing.JOptionPane.ERROR_MESSAGE);
} finally {
    txtContrasena.setText("");
    txtConfirmacion.setText("");
}
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblConfirmacion;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JPasswordField txtConfirmacion;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbUsuarios;
    private com.toedter.calendar.JDateChooser dcNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNickname;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
