/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import logica.ControladorUsuario;

/**
 *
 * @author adrie
 */
public class InternalAltaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalAltaUsuario
     */
    private ControladorUsuario control;
    
    
    
    
    public InternalAltaUsuario(ControladorUsuario control) {
    initComponents();
    FechasFormulario.configurar(dcNacimiento);
    this.control = control;

    // Estado inicial de selección de Instituto
    cmbInstituto.setEnabled(false);
    cargarInstitutos();
}

    private void cargarInstitutos() {
    cmbInstituto.removeAllItems();
    cmbInstituto.addItem("Seleccione un Instituto...");
    try {
            // Asume que agregas este método en ControladorUsuario
            java.util.List<String> institutos = control.obtenerNombresInstitutos();
            for (String nombreInst : institutos) {
                cmbInstituto.addItem(nombreInst);
            }
        } catch (Exception e) {
            System.out.println("Error al cargar institutos: " + e.getMessage());
        }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbInstituto = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        chkDocente = new javax.swing.JCheckBox();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        dcNacimiento = new com.toedter.calendar.JDateChooser();

        lblContrasena = new javax.swing.JLabel();
        lblConfirmacion = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        txtConfirmacion = new javax.swing.JPasswordField();
        lblContrasena.setText("Contraseña:");
        lblConfirmacion.setText("Confirmar contraseña:");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alta de Usuario");
        setToolTipText("");

        jLabel1.setText("Nickname:");

        jLabel2.setText("Ingrese los siguientes datos");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Correo:");

        txtNickname.addActionListener(this::txtNicknameActionPerformed);

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        txtCorreo.addActionListener(this::txtCorreoActionPerformed);

        jLabel7.setText("Fecha de nacimiento");

        cmbInstituto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbInstituto.addActionListener(this::cmbInstitutoActionPerformed);

        jLabel8.setText("Instituto");

        chkDocente.setText("Es docente");
        chkDocente.addActionListener(this::chkDocenteActionPerformed);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(lblContrasena)
                        .addComponent(lblConfirmacion)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNickname, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(txtConfirmacion, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(dcNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(cmbInstituto, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                    .addContainerGap())
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(chkDocente)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnAceptar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnCancelar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasena)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmacion)
                    .addComponent(txtConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dcNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDocente)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap()
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbInstitutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbInstitutoActionPerformed

    private void chkDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDocenteActionPerformed
        boolean esDocente = chkDocente.isSelected();
    cmbInstituto.setEnabled(esDocente);
    if (!esDocente) {
        cmbInstituto.setSelectedIndex(0);
    }
    }//GEN-LAST:event_chkDocenteActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
    String clave = new String(txtContrasena.getPassword());
    String confirmacion = new String(txtConfirmacion.getPassword());
    try {
        String nickname = txtNickname.getText().trim();
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String correo = txtCorreo.getText().trim();
        java.time.LocalDate fechaNac = FechasFormulario.leer(dcNacimiento, "la fecha de nacimiento");
        if (chkDocente.isSelected()) {
            String instituto = cmbInstituto.getSelectedIndex() > 0
                    ? (String) cmbInstituto.getSelectedItem() : null;
            control.registrarDocente(nickname, correo, nombre, apellido, fechaNac,
                    instituto, clave, confirmacion);
        } else {
            control.registrarEstudiante(nickname, correo, nombre, apellido, fechaNac,
                    clave, confirmacion);
        }
        javax.swing.JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente.");
        limpiarFormulario();
    } catch (IllegalArgumentException e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                "Revise los datos", javax.swing.JOptionPane.WARNING_MESSAGE);
    } catch (RuntimeException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "No se pudo registrar el usuario.",
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } finally {
        txtContrasena.setText("");
        txtConfirmacion.setText("");
    }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicknameActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose(); // Cierra la ventana interna actual
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed


    private void limpiarFormulario() {
    txtNickname.setText("");
    txtNombre.setText("");
    txtApellido.setText("");
    txtCorreo.setText("");
    dcNacimiento.setDate(null);
    chkDocente.setSelected(false);
    cmbInstituto.setSelectedIndex(0);
    cmbInstituto.setEnabled(false);
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblConfirmacion;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JPasswordField txtConfirmacion;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox chkDocente;
    private javax.swing.JComboBox<String> cmbInstituto;
    private com.toedter.calendar.JDateChooser dcNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNickname;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
