/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;


import java.time.format.DateTimeFormatter;
import java.util.List;
import logica.ControladorUsuario;
import logica.IServidorCentral;

/**
 *
 * @author adrie
 */
public class InternalConsultaUsuario extends javax.swing.JInternalFrame {

    private ControladorUsuario control;
    private IServidorCentral servidorCentral;
    private java.awt.image.BufferedImage imagenUsuario;
    
    public InternalConsultaUsuario(ControladorUsuario control,IServidorCentral servidorCentral) {
        initComponents();
        this.control = control;
        this.servidorCentral = servidorCentral;
        

        cargarUsuariosEnCombo();

        setTitle("Consulta de usuario");
        setSize(980, 500);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(true);
    }

    
    
    
    private void cargarUsuariosEnCombo() {
    cmbUsuarios.removeAllItems();
    List<String> nickname = control.listarNicknamesUsuarios();
    
    for (String nick : nickname) {
        cmbUsuarios.addItem(nick);
    }
    
    // Dejamos la selección vacía al principio para que no cargue datos por accidente
    cmbUsuarios.setSelectedIndex(-1); 
}
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel("Sin imagen", javax.swing.SwingConstants.CENTER);
        lblImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagenMouseClicked(evt);
            }
        });
        cmbUsuarios = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtFechaNac = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setPreferredSize(new java.awt.Dimension(280, 160));
        lstCursosEdiciones = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane2.setPreferredSize(new java.awt.Dimension(280, 160));
        lstProgramas = new javax.swing.JList<>();
        jScrollPaneEdiciones = new javax.swing.JScrollPane();
        jScrollPaneEdiciones.setPreferredSize(new java.awt.Dimension(280, 160));
        lstEdicionesDocente = new javax.swing.JList<>();
        btnSalir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta Usuario");

        jLabel1.setText("Seleccionar Usuario");

        cmbUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUsuarios.addActionListener(this::cmbUsuariosActionPerformed);

        txtNombre.setEditable(false);

        txtApellido.setEditable(false);

        txtMail.setEditable(false);

        txtFechaNac.setEditable(false);

        lstCursosEdiciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCursosEdiciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCursosEdicionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstCursosEdiciones);

        lstProgramas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstProgramas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProgramasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstProgramas);

        lstEdicionesDocente.setModel(new javax.swing.DefaultListModel<>());
        lstEdicionesDocente.setBorder(javax.swing.BorderFactory.createTitledBorder("Ediciones en las que participa"));
        lstEdicionesDocente.setToolTipText("Doble clic en una edición para consultar sus datos");
        lstEdicionesDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEdicionesDocenteMouseClicked(evt);
            }
        });
        jScrollPaneEdiciones.setViewportView(lstEdicionesDocente);
        jScrollPaneEdiciones.setVisible(false);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagen, javax.swing.GroupLayout.Alignment.TRAILING, 120, 120, 120)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombre)
                                .addComponent(txtApellido)
                                .addComponent(txtMail)
                                .addComponent(txtFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneEdiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup().addGap(80).addComponent(lblImagen, 120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneEdiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(btnSalir)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuariosActionPerformed
imagenUsuario = null;
lblImagen.setToolTipText(null);
lblImagen.setCursor(java.awt.Cursor.getDefaultCursor());
lblImagen.setIcon(null);
lblImagen.setText("Sin imagen");
txtNombre.setText("");
txtApellido.setText("");
txtMail.setText("");
txtFechaNac.setText("");
javax.swing.DefaultListModel<String> academico = new javax.swing.DefaultListModel<>();
javax.swing.DefaultListModel<String> programas = new javax.swing.DefaultListModel<>();
lstCursosEdiciones.setModel(academico);
lstProgramas.setModel(programas);
javax.swing.DefaultListModel<String> ediciones = new javax.swing.DefaultListModel<>();
lstEdicionesDocente.setModel(ediciones);
jScrollPaneEdiciones.setVisible(false);
if (cmbUsuarios.getSelectedItem() == null) return;
try {
    String nick = cmbUsuarios.getSelectedItem().toString();
    logica.Usuario usuario = control.obtenerUsuarioPorNickname(nick);
    if (usuario == null) throw new IllegalArgumentException("El usuario ya no existe.");
    mostrarImagen(nick);
    txtNombre.setText(usuario.getNombre());
    txtApellido.setText(usuario.getApellido());
    txtMail.setText(usuario.getMail());
    txtFechaNac.setText(usuario.getFechaNacimiento() == null ? "No registrada"
            : usuario.getFechaNacimiento().format(DateTimeFormatter.ofPattern("dd/MM/uuuu")));
    boolean docente = usuario instanceof logica.Docente;
    jScrollPaneEdiciones.setVisible(docente);
    if (docente) {
        for (String nombre : control.listarEdicionesDocente(nick)) ediciones.addElement(nombre);
    }
    lstCursosEdiciones.setBorder(javax.swing.BorderFactory.createTitledBorder(
            docente ? "Cursos del docente" : "Ediciones inscriptas"));
    lstProgramas.setBorder(javax.swing.BorderFactory.createTitledBorder(
            docente ? "Programas relacionados con sus cursos" : "Programas inscriptos"));
    for (String nombre : control.listarCursosOEdicionesUsuario(nick)) academico.addElement(nombre);
    for (String nombre : control.listarProgramasUsuario(nick)) programas.addElement(nombre);
} catch (RuntimeException e) {
    e.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "No se pudo completar la consulta: "
            + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_cmbUsuariosActionPerformed

    private void lstCursosEdicionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCursosEdicionesMouseClicked
if (evt.getClickCount() != 2 || lstCursosEdiciones.getSelectedValue() == null
        || cmbUsuarios.getSelectedItem() == null || getDesktopPane() == null) return;
try {
    String nombre = lstCursosEdiciones.getSelectedValue();
    logica.Usuario usuario = control.obtenerUsuarioPorNickname(cmbUsuarios.getSelectedItem().toString());
    if (usuario == null) throw new IllegalArgumentException("El usuario ya no existe.");

    javax.swing.JInternalFrame ventana;
    if (usuario instanceof logica.Docente) {
        ConsultaCurso consulta = new ConsultaCurso(servidorCentral);
        consulta.seleccionarCurso(nombre);
        ventana = consulta;
    } else {
        ConsultaEdicionDeCursoInternalFrame consulta = new ConsultaEdicionDeCursoInternalFrame(servidorCentral);
        consulta.seleccionarEdicion(nombre);
        ventana = consulta;
    }
    getDesktopPane().add(ventana);
    ventana.setVisible(true);
    ventana.toFront();
} catch (RuntimeException e) {
    e.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "No se pudo abrir la consulta: " + e.getMessage());
}
    }//GEN-LAST:event_lstCursosEdicionesMouseClicked

    private void lstProgramasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProgramasMouseClicked
if (evt.getClickCount() != 2 || lstProgramas.getSelectedValue() == null || getDesktopPane() == null) return;
try {
    ConsultaProgramaFormacionInternalFrame ventana = new ConsultaProgramaFormacionInternalFrame(servidorCentral);
    ventana.seleccionarPrograma(lstProgramas.getSelectedValue());
    getDesktopPane().add(ventana);
    ventana.setVisible(true);
    ventana.toFront();
} catch (RuntimeException e) {
    e.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "No se pudo abrir el programa: " + e.getMessage());
}
    }//GEN-LAST:event_lstProgramasMouseClicked

    private void mostrarImagen(String nick) {
        try {
            byte[] datos = servidorCentral.obtenerImagenUsuario(nick);
            if (datos == null) return;
            java.awt.image.BufferedImage imagen = javax.imageio.ImageIO.read(new java.io.ByteArrayInputStream(datos));
            if (imagen == null) throw new java.io.IOException("Imagen no válida");
            double escala = Math.min(116.0 / imagen.getWidth(), 116.0 / imagen.getHeight());
            lblImagen.setIcon(new javax.swing.ImageIcon(imagen.getScaledInstance(
                    Math.max(1, (int) (imagen.getWidth() * escala)),
                    Math.max(1, (int) (imagen.getHeight() * escala)), java.awt.Image.SCALE_SMOOTH)));
            lblImagen.setText("");
            imagenUsuario = imagen;
            lblImagen.setToolTipText("Doble clic para ver la imagen más grande");
            lblImagen.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        } catch (Exception e) {
            lblImagen.setText("Imagen no disponible");
        }
    }

    private void lblImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenMouseClicked
        if (evt.getClickCount() != 2 || imagenUsuario == null
                || cmbUsuarios.getSelectedItem() == null || getDesktopPane() == null) return;
        javax.swing.JInternalFrame ventana = new javax.swing.JInternalFrame(
                "Imagen de " + cmbUsuarios.getSelectedItem(), true, true, true, true);
        javax.swing.JLabel imagen = new javax.swing.JLabel(new javax.swing.ImageIcon(imagenUsuario));
        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ventana.add(new javax.swing.JScrollPane(imagen));
        ventana.setSize(Math.min(750, Math.max(300, imagenUsuario.getWidth() + 40)),
                Math.min(600, Math.max(250, imagenUsuario.getHeight() + 60)));
        getDesktopPane().add(ventana);
        ventana.setVisible(true);
        ventana.toFront();
    }//GEN-LAST:event_lblImagenMouseClicked

    private void lstEdicionesDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEdicionesDocenteMouseClicked
        if (evt.getClickCount() != 2 || !jScrollPaneEdiciones.isVisible()
                || getDesktopPane() == null) return;
        int indice = lstEdicionesDocente.locationToIndex(evt.getPoint());
        if (indice < 0 || !lstEdicionesDocente.getCellBounds(indice, indice).contains(evt.getPoint())) return;
        try {
            ConsultaEdicionDeCursoInternalFrame ventana = new ConsultaEdicionDeCursoInternalFrame(servidorCentral);
            ventana.seleccionarEdicion(lstEdicionesDocente.getModel().getElementAt(indice));
            getDesktopPane().add(ventana);
            ventana.setVisible(true);
            ventana.toFront();
        } catch (RuntimeException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo abrir la edición: "
                    + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lstEdicionesDocenteMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstCursosEdiciones;
    private javax.swing.JList<String> lstProgramas;
    private javax.swing.JScrollPane jScrollPaneEdiciones;
    private javax.swing.JList<String> lstEdicionesDocente;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
