/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tarea_1_prog_app;

import java.util.ArrayList;

/**
 *
 * @author Chama
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private Controlador controlador;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Controlador controlador) 
    {
        this.controlador = controlador;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    private ArrayList<Curso> cursos = new ArrayList<>();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        txtArchivo = new javax.swing.JMenu();
        txtSalir = new javax.swing.JMenuItem();
        txtUsuarios = new javax.swing.JMenu();
        txtAltaUsuario = new javax.swing.JMenuItem();
        txtConsultaUsuario = new javax.swing.JMenuItem();
        txtModificarUsuario = new javax.swing.JMenuItem();
        txtCursos = new javax.swing.JMenu();
        txtAltaCurso = new javax.swing.JMenuItem();
        txtConsultaCurso = new javax.swing.JMenuItem();
        txtAltaEdicionCurso = new javax.swing.JMenuItem();
        txtConsultaEdicionCurso = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        txtArchivo.setText("Archivo");

        txtSalir.setText("Salir");
        txtArchivo.add(txtSalir);

        jMenuBar1.add(txtArchivo);

        txtUsuarios.setText("Usuarios");

        txtAltaUsuario.setText("Alta de usuario");
        txtAltaUsuario.addActionListener(this::txtAltaUsuarioActionPerformed);
        txtUsuarios.add(txtAltaUsuario);

        txtConsultaUsuario.setText("Consulta de usuario");
        txtConsultaUsuario.addActionListener(this::txtConsultaUsuarioActionPerformed);
        txtUsuarios.add(txtConsultaUsuario);

        txtModificarUsuario.setText("Modificar usuario");
        txtModificarUsuario.addActionListener(this::txtModificarUsuarioActionPerformed);
        txtUsuarios.add(txtModificarUsuario);

        jMenuBar1.add(txtUsuarios);

        txtCursos.setText("Cursos");

        txtAltaCurso.setText("Alta de curso");
        txtAltaCurso.addActionListener(this::txtAltaCursoActionPerformed);
        txtCursos.add(txtAltaCurso);

        txtConsultaCurso.setText("Consulta de curso");
        txtConsultaCurso.addActionListener(this::txtConsultaCursoActionPerformed);
        txtCursos.add(txtConsultaCurso);

        txtAltaEdicionCurso.setText("Alta de edición de curso");
        txtAltaEdicionCurso.addActionListener(this::txtAltaEdicionCursoActionPerformed);
        txtCursos.add(txtAltaEdicionCurso);

        txtConsultaEdicionCurso.setText("Consulta de edición de curso");
        txtCursos.add(txtConsultaEdicionCurso);

        jMenuBar1.add(txtCursos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltaUsuarioActionPerformed

    private void txtAltaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltaCursoActionPerformed
        // TODO add your handling code here:
        
        AltaCurso ventanaAltaCurso = new AltaCurso(controlador);
        
        jDesktopPane1.add(ventanaAltaCurso);
        
        ventanaAltaCurso.setVisible(true);
        
        System.out.println("Hice click en Alta Curso");
    }//GEN-LAST:event_txtAltaCursoActionPerformed

    private void txtConsultaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaCursoActionPerformed
        // TODO add your handling code here:
        
        ConsultaCurso ventanaConsultaCurso = new ConsultaCurso(controlador);
        
        jDesktopPane1.add(ventanaConsultaCurso);
        
        ventanaConsultaCurso.setVisible(true);
    }//GEN-LAST:event_txtConsultaCursoActionPerformed

    private void txtAltaEdicionCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltaEdicionCursoActionPerformed
        // TODO add your handling code here:
        
        AltaEdicionCurso ventanaAltaEdicionCurso = new AltaEdicionCurso();
        
        jDesktopPane1.add(ventanaAltaEdicionCurso);
        
        ventanaAltaEdicionCurso.setVisible(true);
    }//GEN-LAST:event_txtAltaEdicionCursoActionPerformed

    private void txtConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaUsuarioActionPerformed

    private void txtModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem txtAltaCurso;
    private javax.swing.JMenuItem txtAltaEdicionCurso;
    private javax.swing.JMenuItem txtAltaUsuario;
    private javax.swing.JMenu txtArchivo;
    private javax.swing.JMenuItem txtConsultaCurso;
    private javax.swing.JMenuItem txtConsultaEdicionCurso;
    private javax.swing.JMenuItem txtConsultaUsuario;
    private javax.swing.JMenu txtCursos;
    private javax.swing.JMenuItem txtModificarUsuario;
    private javax.swing.JMenuItem txtSalir;
    private javax.swing.JMenu txtUsuarios;
    // End of variables declaration//GEN-END:variables
}
